[package]
name = "lazy-mmdb"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "lazy-mmdb"
path = "src/main.rs"

[dependencies]
dotenvy = "0.15"
fancy-log = "0.1"
lazy-motd = "1"
tokio = { version = "1", features = ["full"] }